### ISSUE TITLE
Crashes in Beta version

### ISSUE THREAD

**Issue by SauROnmiKE** [Enginecrafter77/SurvivalInc#1]
Hi there! First of all I'd like to thank you for picking up where Schoperation left his mod.

I just downloaded the new version you uploaded and both my server and client cannot go through world generation, they crash on world loading, producing the same crash report seen here (for some reason single player also produces a server crash report?) : https://pastebin.com/AekTiMsr

Also, some things I wanted to point out from the alpha version, which I don't know if they are fixed here:
1. Wetness bar stayed still, about at 10% even though I tried to use a completely dry towel.
2. Wetness bar never rose again although I did have the effects of wetness.
3. Mod crashes when I disabled wetness.

That's all I found so far. Thanks for your time, have a good day and stay safe!

*EDIT: Mistakenly posted the server's side of the crash, although it's the same as the client's

**Comment by Enginecrafter77** [comment]
First of all, I would like to thank you the time you took on writing this issue.

Now, to address your problems. In the crash report, I can see that you have several other mods installed. At first sight, I suspect that maybe some mod registers their biome temperature in later loading stages, so their original values are not cached yet. I am going to try to move the caching code to later stages (for example at server/client startup).

But if it's not that case, I will have to try to replicate the mod setup you use (it would help a lot if you posted a link to your zipped mods and config folder, so I can replicate your setup 1:1) so I can address the issue closer.

Also, about the individual issues:

1. The towel is supposed to "equalize" your wetness and it's wetness. That means when you have around 20% wetness, the towel absorbs just half of it so you and the towel have both 10%. This corelates with the real behaviour of towels. I mean, like imagine if you used 99% wet towel to pull that 1% wetness off you. In reality, it would just dry the towel and transfer the wetness onto you. That is what the towel does in the mod. So to your case, under 10% the towels tend to have negligible effect. To dry off your remaining wetness, stand near fire or lava.
2. What do you mean by "never rose when I have wentess effects"? You mean like the slowdown? Or  the drops?
3. This one is undoubtely a serious issue. I will look at it asap.

**Comment by Enginecrafter77** [comment]
Okay, so I replicated your modpack as close as possible, and did some tests there. After going through the crashes you described, I tried to fix them. After that, I tested it by disabling individual stats, and everything worked as expected. As such, I am closing this issue. If these start reoccurring to you, you can reopen it.

**Comment by SauROnmiKE** [comment]
I really appreciate all the trouble you went through for this. It was night for me at the time, otherwise I would have uploaded a zip with the mods and save you all this time :/

Client works great. No crashes on world gen, no crashes when disabling stuff. Server gets this error on startup: https://pastebin.com/3x7HPdhS, but I do not think it has anything to do with the mod. I am using a Magma server, Forge-Paper hybrid. It had some plugin issues that should be working, maybe it has issues with mods too. Give it a read though, maybe it is something completely different.

Thanks again for your time and quick response.

**Comment by Enginecrafter77** [comment]
Ok yeah, silly me. I thought marking it as client only would just strip it away from server, as server doesn't need to keep track of client only configuration. Gonna fix it now. Thanks for pointing it out.

**Comment by SauROnmiKE** [comment]
Thanks again for the super-quick response! I'll try it out in the next few hours and let you know how it goes.
