### ISSUE TITLE
Cold too lethal

### ISSUE THREAD

**Issue by Creeper2006** [Enginecrafter77/SurvivalInc#10]
My village is far from my spawn, and it was winter. I FROZE to death in a house and then when I respawned, the body heat bar went down so fast, I was dead in about 30 seconds. I do not know how to make it harder for me to die due to body heat, but either you need to add cheap clothes, or make it harder for everyone to die by cold. I had to break my SURVIVAL PROMISE, and I still died after my ghast pet shot a fireball. Once the fires went out, I died in 30 seconds or so. So can you please add warm (and cold) clothing into the game AND make it harder to die by cold? Thanks.

**Comment by Enginecrafter77** [comment]
Well, you can tune the value of "Heat Exchange Factor" under Heat config, which basically changes the base rate of how quickly your body heat changes. This makes it harder to die because if body heat. Also, there are already ways to get yourself warm quickly. I also plan on adding cheap alternative to flint and steel, a wooden igniting kit. It would require some time to use (like bow animation), but it would be enough to keep you warm. The problem are excessive temperatures, agains which there is currently no effective protection mechanism.

**Comment by Creeper2006** [comment]
Ok. Do you also mind making it 1. default harder to losing sanity (I
knowhow to change it, but config has a tendency to change back to default
every time I exit minecraft). I would also like clothing, and water is
notorious for making me REALLY SLOW. You should also have a system like
tough as nails, where water is bad unless you purify it. Water really isn't
a problem. I do have trouble heating myself up, because in the middle of
winter, I freeze to death before I can find iron. Furnace? Nah. I die
before I even have a wooden pickaxe. But apart from that, no other
complaints! :D

**Comment by Enginecrafter77** [comment]
About that config with tendecy to reset...

I didn't spot this issue before. Could you please post your game log (on pastebin) when that happens? (2 logs actually; from the game when the config was reset and from the game before).

Also, about the water. It is already on the TODO list. You can actually see an indicator when you hover over the canteen idicating water quality. This value will be used in the future to apply effects like they used to in SchopCraft.

**Comment by Creeper2006** [comment]
It may not be the config, it could just be the controls. The controls reset
on "secret rooms". I just assumed config reset. It happens occasionally.
It's just that it dosent seem to save sometimes with mods. I used open
modular turrets and set the RF usage per shot all to 1, and it reset next
time I entered minecraft. It happens everywhere and I assume it has nothing
to do with the mods and more to do with minecraft. Also, I cannot due to
parent reasons, also also, I cannot do it cuz I do not know HOW to do it.
Config in all mods probably resets because my PC is overloaded. I have
deleted some and maybe that fixes the issue (I think I have room for one
more, so...)


Also also also, (this is out of subject) do you know any tanks mod that's
1.12.2 and IS NOT related to Flan's mod?

**Comment by Enginecrafter77** [comment]
Okay so I assume the disappearing config is not a problem of the mod (also considering the fact the config follows forge guidelines and nobody else has reported this problem).

About the last question, sorry, this is far too off the context. I can't think of any such mod anyways.

**Comment by Creeper2006** [comment]
well, thanks. Consider my suggestions, and have a nice day.

**Comment by gatoborrachon** [comment]
> Also also also, (this is out of subject) do you know any tanks mod that's 1.12.2 and IS NOT related to Flan's mod?
@Creeper2006 
i just want to answer his question if he stills looking for a mod:

Immersive Vehicles:
https://www.curseforge.com/minecraft/mc-mods/minecraft-transport-simulator

that mod evolved a lot over the years, there are a lot of community packs with many different vehicles (tanks included, with weapons)

**Comment by Creeper2006** [comment]
Thanks
