### ISSUE TITLE
Compatiblity with Serene Seasons

### ISSUE THREAD

**Issue by hazerddex** [Enginecrafter77/SurvivalInc#11]
serene season
i like this mods snow thaw effects, but i also want to keep the crop, grass and leaf color change that Serene season comes with.  the main problem is that they don't share seasons.

basically what i mean is if i use serene season and this mod. winter in this mod can happen when it's summer in serene season.

~Tinker construct Smeltery should provide warmth when it's full of lava. Same with the holding tank for molten metals.~ (**Edit by EC77**: Issue addition out of context. Please open separate issue.)

**Comment by Enginecrafter77** [comment]
First, welcome to the project!

Second; If I inderstand you right, you want Survival Inc seasons to work alongside Serene Seasons, right? Well, I suppose I could give it a try, but I can't think of any sane reason why it would be worth it.

Anyways, I have added this issue to the Compatibility module project.

**Comment by hazerddex** [comment]
> First, welcome to the project!
> 
> Second; If I inderstand you right, you want Survival Inc seasons to work alongside Serene Seasons, right? Well, I suppose I could give it a try, but I can't really think of an easy and elegant solution other than spliiting the season config even more.
> 
> Anyways, I have added this issue to the Compatibility module project, so I will consider this when I will be working on that.

basically i just want to be able to sync the seasons so i don't have it be winter while it's summer in serene seasons  the easiest solution would be to just add the ability to choose what season you start in for a new world.

**Comment by Enginecrafter77** [comment]
Yeah I guess that could possibly work. I will probalbly add a config about in which season you normally start.

But there is one thing that still concerns me. I don't know how Serene Season forces snowing in normally-warm-enough biomes (think of snow in classic forest). I mean, I am a little bit afraid Survival Inc. would clash with Serene Seasons over the biome temperature, which would most probably result in the temperatures being incorrect (for example, one biome executed Survival Inc's provider last, while other one executes Serene Seasons last [the last always prevails]).

**Comment by Enginecrafter77** [comment]
Okay so, today I reviewed the issue, and it seems that I pretty much forgot about this, but somehow I kept it in back of my mind. I made [this commit](https://github.com/Enginecrafter77/SurvivalInc/commit/eacc88793b6e35d3f80467f47d0965e1a9b2f7ee), which pretty much adds what you want. You can now specify the starting season and day in the config. This commit is already included in the [latest release](https://github.com/Enginecrafter77/SurvivalInc/releases/tag/v1.1.5), so you might as well give it a try. The seasons will probably still get out of sync at one point, but I can do little about that. As such, I am closing this issue as solved.
