### ISSUE TITLE
Per Dimension Options for Seasons

### ISSUE THREAD

**Issue by mxnmnm** [Enginecrafter77/SurvivalInc#15]
I want to be able to disable seasons in specific dimensions and maybe even configure the season length per dimension.

**Comment by Enginecrafter77** [comment]
Seasons are supposed to be overworld-only. Maybe also for overworld-like dimensions, but certainly not for nether or end, or similar "alien" dimensions.

**Comment by Enginecrafter77** [comment]
I don't know why I kept overlooking this issue. But I noticed this has been solved way back in d6bb686a06d4d39b723097fd06c2d8fecd3a6e74. So I'm closing this issue, as it shouldn't be relevant anymore.
