### ISSUE TITLE
More Things Impacting Sanity

### ISSUE THREAD

**Issue by mxnmnm** [Enginecrafter77/SurvivalInc#16]
**Is your feature request related to a problem? Please describe.**
Sanity should be impacted by more things

**Describe the solution you'd like**
I would like an item sanity map so whenever an item is in your hotbar/hand it helps improve/decrease your sanity (being in your hand should improve more than hotbar) and a block sanity map (whenever you are within x blocks of this block your sanity gets a increased/reduced by y amount)

**Comment by Enginecrafter77** [comment]
I think it should be safe to close this since it's pretty much solved as of https://github.com/Enginecrafter77/SurvivalInc/commit/94ff923acea6fd86b2a9ca1fc11629ff6234e9e2.
