### ISSUE TITLE
[Suggestion] Have Rain Increase Wetness Levels

### ISSUE THREAD

**Issue by mxnmnm** [Enginecrafter77/SurvivalInc#18]
**Is your feature request related to a problem? Please describe.**
The rain should increase the player's wetness levels.

**Describe the solution you'd like**
Have the rain increase the player's wetness levels.

**Describe alternatives you've considered**
Not have the rain increase the player's wetness levels but that doesn't make sense.

**Comment by Enginecrafter77** [comment]
Already implemented (see [here](https://github.com/Enginecrafter77/SurvivalInc/blob/master/src/main/java/enginecrafter77/survivalinc/stats/impl/WetnessModifier.java#L42)]. It's just kinda slow and hence hard to actually notice, so I will probably make a config option for that.
