### ISSUE TITLE
Add support for custom entries.

### ISSUE THREAD

**Issue by KubiRem** [Enginecrafter77/SurvivalInc#2]
Add support for custom entries. For example blocks etc.

**Comment by Enginecrafter77** [comment]
What entries do you mean?

**Comment by KubiRem** [comment]
Custom blocks, machines from other mods etc.

**Comment by KubiRem** [comment]
Custom blocks - modded blocks.
Entries - custom files for modpack dev. (I am a developer of mocpack)

**Comment by Enginecrafter77** [comment]
I am sorry, but I am still not 100% sure what you mean. If you mean like to add more mod content related to blocks, this is currently being done and more are on the TODO list.

**Comment by KubiRem** [comment]
Ok
