### ISSUE TITLE
[Crash] Issue with HBM's Nuclear Tech Mod

### ISSUE THREAD

**Issue by gatoborrachon** [Enginecrafter77/SurvivalInc#23]
**Short Description**
When the game tries to render your body when you are a ghost, the game crashes

**To Reproduce**
1. Play with [HBM's Nuclear Tech Mod](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/releases) and Survival Inc.
2. Die
3. Press "E" or "F5"

**Crash Report**
https://pastebin.com/PdvPbYG0

**Additional Notes**
Tell me if this is fault of HBM's Nuclear Tech Mod to open an issue in their Github

**Comment by Enginecrafter77** [comment]
Oh, I see. I think I know why the crash happens. The HBM's NT developers assume that player is **always** rendered using a class extending RenderPlayer. SurvivalInc uses a custom renderer to render ghosts so the cast fails there. I am currently working on circumventing this issue, and it looks good so far. I just have to run some real tests.

**Comment by Enginecrafter77** [comment]
Hi, I have looked into the crash report, but it seems that the file where the crash happens (ModEventHandlerClient.java:1091) is no longer the same (on github, it has just about 216 lines). What I am trying to say is that try to specify which version you're using, and maybe try updating to see if the crash hasn't been resolved on their side. Because unless I can look up their source code at that point where it crashes, my hands are tied in this.

**Comment by gatoborrachon** [comment]
oh sorry, i forgot to tell you to check the [`1.12.2-test` branch](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/1.12.2_test/com/hbm/main/ModEventHandlerClient.java#L1091)

i remember that something similar happened with the mod [Ido](https://www.curseforge.com/minecraft/mc-mods/ido), maybe its more fault from HBM's Nuclear Tech Mod than yours, but when Ido mod switched to use [Obfuscate](https://www.curseforge.com/minecraft/mc-mods/obfuscate) that issue stopped, i think i need to open an issue in HBM's Nuclear Tech Mod github.

if you want to see the changelog of Ido, here is it:
https://www.curseforge.com/minecraft/mc-mods/ido/files/3096693

**Comment by Enginecrafter77** [comment]
Okay I will take a look on that. Also, there is no need to open up an issue on their side yet, it might be my fault as well (I just can't see anything wrong with my code at this moment, that's why I have to investigate this further.)

**Comment by gatoborrachon** [comment]
ok, let me open that issue, i wil link this one reffering to your comment, and if you want to build a workspace with HBM's Nuclear Tech Mod, use the "gradle" folder and "build.gradlew" file from any other 1.12 mod you worked on and then see the readme of that mod, you know that forge likes to break things and the porter of that mod forgot to upload that file, but its a minor issue

**Comment by Enginecrafter77** [comment]
Well, I am going to make a PR to that mod, so I will be commenting on your issue soon. I think I will also add the gradle build system in the PR, setting it up every time from scratch is such a pain in ass.

**Comment by Enginecrafter77** [comment]
The pull request with the patch has been merged to HBM's source tree. As such, I am closing this issue as solved.

**Comment by gatoborrachon** [comment]
ok, thanks for all
