### ISSUE TITLE
[Request] More intuitive temperature feedback/warning

### ISSUE THREAD

**Issue by Griiimon** [Enginecrafter77/SurvivalInc#24]
Problem:

It's not clear which range of temperatures are considered safe. Also there has to be a more visible warning if you cross a certain temperature threshold.

Solution:

1. Make the heat gui bar more flexible. It could change color from blue (at very low temps) to turquiose (low) over green (comfortable) to yellow (getting very warm) and red (hot).

2. Also maybe a (shader?) effect when crossing a temperature threshold towards freezing/overheating. Something as simple as a blue/red tint should suffice.

Btw, do shader effects stack so the sanity shader would still work?

Additional Request:

3. Have a thermometer icon which indicates the temperature of the environment. The players temperature should imho converge much slower to the environment temperature than what's the default heat exchange setting. But that means he should know where it is converging to in his current location, so he is able to react accordingly. 

4. Another idea is to somehow include the environment temperature display in the heat bar. A crude approach would be to just add a vertical line. A more visual pleasing one may be to outline the empty or filled icons according to temperature.

**Comment by Enginecrafter77** [comment]
Wait that commit fixes only point 1. This issue is far from resolved.

**Comment by gatoborrachon** [comment]
the point 2 and the latest commit are the same as my issue isn't?
https://github.com/Enginecrafter77/SurvivalInc/issues/37

should i close my issue too? mine could be a duplicated, just that it uses the [Heat and Climate Lib](https://github.com/defeatedcrow/HeatAndClimateLib/blob/1.12.2_v3/README.md#function), but i think you have considered all the options and the best one for Survival Inc. is to have its own Heat Vignette, no problem, i prefer a working mod that a weak-foundation one.

**Comment by Enginecrafter77** [comment]
@gatoborrachon Oh damn I forgot to disable it for creative mode. Well, I guess v1.2.8 won't live that long after all.

Also, sorry for not implementing it the HaC way. I'm still struggling to come up with how those two could possibly work in harmony without one wreaking havoc into the another.

**Comment by gatoborrachon** [comment]
> Well, I guess v1.2.8 won't live that long after all.

i think that this could be added in the next release, but idk

-

> Also, sorry for not implementing it the HaC way. I'm still struggling to come up with how those two could possibly work in harmony without one wreaking havoc into the another.

no problem, if the language barrier and the lack of documentation doesn't make it easy, i think we can ask directly to DefeatedCrow or just let this in Long Term

the main compat-feature that i came to my mind in these moments was to, instead of using the Biome temperature, use the [Heat Tiers](https://defeatedcrow.jp/modwiki/HaCLib_HeatTier) (translate the page with Google) which also take the Biome Temperature but it adds its Heat Tier blocks (Which has auto-compat for modded fluids' temperature, and where one can add compat with other mods' heat blocks), along with the Gauss Scaling of Hot Blocks and the Heat Exchange Rate from Survival Inc.

**Comment by gatoborrachon** [comment]
oh, also, adding the same shader when you are too hot or cold but for de-hydration (a gray-ish color) would be helpful too

**Comment by Enginecrafter77** [comment]
Points 3 and 4 will be added to project, but are a bit out of context of this issue so I will close it.
