### ISSUE TITLE
[Issue] Crash on startup with HungerOverhaul

### ISSUE THREAD

**Issue by gatoborrachon** [Enginecrafter77/SurvivalInc#25]
**Short Description**
VanillaFix says that there was a crash when loading game and the suspected mods are HungerOverhaul, AppleCore (necessary for HungerOverhaul) and Survival Inc.

**To Reproduce**
1. Add HungerOverhaul, AppleCore and Survival Inc. to mods folder
2. Try to start Minecraft
3. See error

**Crash Report**
https://pastebin.com/mFzGKMQG

**Additional Notes**
HungerOverhaul-1.12.2-1.3.3.jenkins148
AppleCore-mc1.12.2-3.4.0
Survival Inc-1.2.5

**Comment by gatoborrachon** [comment]
well, if this issue its more fault from HungerOverhaul side, maybe i can fix it if you tell me what i need to change, or maybe i can stop using it, it only was to increase the crop growing time. (maybe you can add a config option for this inside Survival Inc., if it fits in the scope of your mod)

**Comment by ACGaming** [comment]
> iguanaman.hungeroverhaul.module.event.HungerOverhaulEventHook.renderTooltips(HungerOverhaulEventHook.java:634)

Try setting addFoodTooltips to false in HungerOverhaul.cfg, line 118. Maybe that could help?

**Comment by Enginecrafter77** [comment]
This issue is definitely my fault; I blindly assumed that the nbt tag is already initialized when that function is being called. But it seems that AppleCore tries to find out whether the canteen is a food or not. It probably does so by calling it on dummy ItemStack without assigning it a NBT. I will fix this as soon as I can.

**Comment by gatoborrachon** [comment]
oh ok, many thanks, i will try it as soon as is released to confirm

**Comment by Enginecrafter77** [comment]
@gatoborrachon You don't need to wait for another release. You can compile the mod yourself anytime you want. If you don't know how to do it (or you don't want to), [here](https://www.dropbox.com/s/2a8j5gk62bc1i99/SurvivalInc-1.2.5-1-ge38edf0.jar?dl=1) is a compiled version with the patch included.

**Comment by gatoborrachon** [comment]
oh no problem, fuck i can't believe i forgot this, i just saw a new release 3 days ago in curseforge, many thanks

**Comment by Enginecrafter77** [comment]
You're welcome!
