### ISSUE TITLE
Crash with AppleSkin

### ISSUE THREAD

**Issue by TheNextJake** [Enginecrafter77/SurvivalInc#28]
**Short Description**
Crashes when hovering on the Canteen item.

**To Reproduce**
1. Instal Survival Inc. and AppleSkin
2. Launch the game
4. Create a new game and hover mouse on the Canteen item
5. Profit [or not]

**Crash Report**
https://pastebin.pl/view/7936225f

**Additional Notes**
Probably because of the canteen being registered as a food item [does not occur with TAN and its drinks]
Does not happen with only AppleCore installed.

**Comment by Enginecrafter77** [comment]
Issues #26 and #27 seem related. Have you tried the version with the latest patch? (Linked in #25)

**Comment by TheNextJake** [comment]
Yeah the latest patch helped. Thanks

**Comment by Enginecrafter77** [comment]
No problem. Seems that I need to make that patch more visible tho.
