### ISSUE TITLE
[Request] Add ability to move HUD elements 

### ISSUE THREAD

**Issue by Duatao7055** [Enginecrafter77/SurvivalInc#29]
**Is your feature request related to a problem? Please describe.**
I do not like the current HUD positions for each thing as they cover other HUD elements from other mods.

**Describe the solution you'd like**
A config option to move each individual HUD element that this mod adds.

**Describe alternatives you've considered**
Remove the textures for this mod using resource packs and guess what my sanity is.

**Additional context**

**Comment by Griiimon** [comment]
Even in vanilla the hydration display hides the bubbles that show your remaining air under water.

**Comment by Enginecrafter77** [comment]
Hmm that's weird. When I was testing the mod in a normal environment it worked fairly well. I tested it with only AppleCore and HungerOverhaul installed (thus the Peckish in top right corner), but it works the same with vanilla. Here is the evidence:

![Screenshot](https://dl.dropboxusercontent.com/s/mwlvcte2muf4vzb/si126.png?dl=1)

Can you provide some screenshot about how it looks like on your side?

**Comment by Griiimon** [comment]
Wow, ok. I take it back. Must be one of my many mods or my changes to the code.

**Comment by Enginecrafter77** [comment]
It's okay, I would like to investigate this further anyways. I surely don't want Survival Inc. to cause any more trouble than necessary (pun intended... ?). What my code does is to translate the Air and Armor bars 10 pixels upwards, which is done using [TranslateRenderFilter](https://github.com/Enginecrafter77/SurvivalInc/blob/master/src/main/java/enginecrafter77/survivalinc/client/TranslateRenderFilter.java). I am not really sure which mods should this be interfering with, it's a pretty straight-forward code. Would you mind sharing your mod list?

**Comment by Griiimon** [comment]
As for me, it was totally my fault. No mods were interfering. I just messed with your code on every possible level. Works fine with all of my mods + your original 1.2.6 version. 
Again, I shouldn't have said anything in the first place.

**Comment by Enginecrafter77** [comment]
Oh, okay. Good to know. But I would still like to know what's wrong on @Duatao7055 's side.

**Comment by Duatao7055** [comment]
My issue is that it covers up the temperature icon from the SimpleDifficulty mod, which does some of the same things this mod does like adding heat and thirst. I'm currently making a modpack and I'm using your mod for its sanity and wetness features, and maybe ghost in the future.

**Comment by Enginecrafter77** [comment]
Okay so this should be solved as of 36c512938fe52aeff8d69848cfcb4e71015aff9c, which adds numerous HUD configuration options.
