### ISSUE TITLE
[Suggestion] Add config options to dictate which blocks can dry towels and Heat conductivity config

### ISSUE THREAD

**Issue by Skorpioon** [Enginecrafter77/SurvivalInc#30]
Hello, basically it would be nice if there was a way to dry towels with blocks other than a working furnace, thank you!
also if you could configure the heat conductivity for other armors, maybe even as an NBT tag or something? Im not sure if that would work, but if can that would be amazing. Along with a way to sorta change the rate at which armors get wet.

**Comment by Enginecrafter77** [comment]
Hi, sorry for the delay but I have been busy for the past few days and I will probably still be busy for the next few weeks. I just wanted to let you know that I am aware of this ticket and I will try to work on it as soon as possible.

**Comment by Enginecrafter77** [comment]
Okay, it should be fixed in https://github.com/Enginecrafter77/SurvivalInc/commit/a3fdfaf979da31262c60838c6669b2368f058cec and https://github.com/Enginecrafter77/SurvivalInc/commit/2c718acd935e47543fc9beba3f47f8d102f1c45c.
