### ISSUE TITLE
[Crash] Issue on server

### ISSUE THREAD

**Issue by gatoborrachon** [Enginecrafter77/SurvivalInc#31]
**Short Description**
well, i can't give much information, a friend hosted my personal modpack on his PC and as soon as i get inside the server it instantly crashes. (but he is already inside the server)

**To Reproduce**
1. Add my [modpack](https://www.mediafire.com/file/vhd5qbhqx61u9em/Mods+Completos+1.12.rar/file) on 2 computers, (if i recall correctly) one will host the server and run minecraft at the same time (PC 1), the other just needs to run minecraft (PC 2)
2. get inside the server in the computer that is hosting the server (PC 1)
3. get inside the server in the other computer (PC 2)

**Crash Report**
Crash 1: https://pastebin.com/BmZiWx3s
Crash 2: https://pastebin.com/g8uecLUz

**Additional Notes**
i never had this issue before, i only played in singleplayer, maybe this is related to running the modpack on a server, but i can't test it by myself ~~(or maybe its related to the other mods, [TF2 Stuff Mod](https://github.com/rafradek/Mods/tree/master/tf2) or Performant (sadly this one is close source, but if you think that it is the guilty mod i can remove it, in words of its author, "the 1.12 version of Performant does not much to increase performance")~~

EDIT: it seems that the second crash report changes the other mods related to the crash, maybe its more related to Survival Inc )

**Comment by gatoborrachon** [comment]
please, tell me this issue is easy to fix, i'm unsure how i can reproduce it by myself to do a binary search, and i wouldn't like to bother my new friend, he works and i just met him today

**Comment by Enginecrafter77** [comment]
I just looked at it and it seems you're right. Damn how could I not notice it? As you said, it was that client-only constructor. I don't know which douchebag decided to mark it client-only. Well, it seems that I will have to unpack all those Vec3d-s to use the common constructor.

**Comment by gatoborrachon** [comment]
oh, ok, well, i will tell this to that friend, thanks

**Comment by Enginecrafter77** [comment]
Just a side note, I came across more server-breaking issues when investigating this, so I recommend you to not use the master branch at this moment until it's fixed.

**Comment by gatoborrachon** [comment]
ok, may thanks, i will wait
