### ISSUE TITLE
[Bug] Sanity Bar is missing when you use Mantle

### ISSUE THREAD

**Issue by gatoborrachon** [Enginecrafter77/SurvivalInc#32]
**Describe the bug**
The Sanity Bar does not show when you use Mantle (Library for Tinkers' Construct)

**To Reproduce**
1. Use Survival Inc and Mantle
2. Enter to a world
3. See error

**Expected behavior**
you will see how the Sanity Bar is missing.

**Screenshots**
With Mantle:
![2021-02-15_20 53 53](https://user-images.githubusercontent.com/61126174/108012836-fab4d300-6fcf-11eb-804f-6737a47f0e83.png)

Without Mantle: 
![2021-02-15_20 59 30](https://user-images.githubusercontent.com/61126174/108013155-b70e9900-6fd0-11eb-99e2-29a2b528df51.png)

**Game Details:**
 * Forge Version: 14.23.5.2854
 * Survival Inc: 1.2.7
 * Additional Mods:
    * Mantle-1.12-1.3.3.55

**Additional Notes**
i have the sanity feature enabled so it's not an user error.

**Comment by Enginecrafter77** [comment]
Hmm, the only thing that comes to my mind is that Mantle tries to deliberately overwrite the space above the hearts. Have you tried changing the sanity bar stack to right? (Under Client config->HUD).

**Comment by gatoborrachon** [comment]
the issue persist: 
![2021-02-16_11 49 24](https://user-images.githubusercontent.com/61126174/108101569-07c3d780-704d-11eb-86b5-2c444e55349a.png)


this is my config:

```
        # The side where the sanity bar will be stacked in
        # Valid values:
        # LEFT
        # RIGHT
        S:sanityBarStack=RIGHT

        # Set to true to enable sanity bar stacking.
        # The stacking basically means that the bar is dynamically integrated into the vanilla HUD.
        # Setting this to false enables absolute positioning using sanityBarX and sanityBarY
        B:stackSanityBar=true
```

**Comment by Enginecrafter77** [comment]
What about the render trigger? Have you tried changing it?

**Comment by gatoborrachon** [comment]
yeah, it seems to fix it (changed to FOOD):
![2021-02-16_11 53 41](https://user-images.githubusercontent.com/61126174/108102029-a6503880-704d-11eb-802a-784d88836c94.png)

**Comment by gatoborrachon** [comment]
what should we do? left this issue fixed by setting for default `S:sanityBarRenderTrigger=FOOD` or i leave it open?

**Comment by Enginecrafter77** [comment]
Oh okay so I probably know what's wrong. Mantle probably cancels the RenderOverlayEvent for FOOD element to disable it from rendering, and renders it's own health bar. But I'm afraid that the fix would probe to be ultimatimatelly contraproductive. So I guess I will probably just add it to known issues since the fix is really easy.

**Comment by gatoborrachon** [comment]
oh, ok, i just wanted to add that the Sanity Bar is forced to be rendered a bit above, but its just a minor issue,
![2021-02-16_12 16 41](https://user-images.githubusercontent.com/61126174/108140025-df58cf00-7086-11eb-86c0-2932a250b45b.png)
