### ISSUE TITLE
[Dev Environment] Can't build a Dev Environment

### ISSUE THREAD

**Issue by gatoborrachon** [Enginecrafter77/SurvivalInc#35]
**Describe the bug**
When you try to run `gradlew setupDecomWorkspace` inside the Dev Environment, you get an error related to the plugin Palantir

**To Reproduce**
1. Download the repo
2. Unzip it
3. Try to run `gradlew setupDecomWorkspace`

**Expected behavior**
Error: https://pastebin.com/WcaFLT9Y
Error with `--stacktrace`: https://pastebin.com/sbhHYyXc

**Comment by Enginecrafter77** [comment]
Oh yeah I see. The error basically says that you don't have the git repository information in the directory. You have to pull the repository using "git clone", not by downloading the zip (or tgz). You can download git for windows from [here](https://git-scm.com/download/win).

Alternatively (if you don't want to download git), you can just comment out/remove lines 17, 25, 82-130 and replace line 22 with something like `version "X.Y.Z"`. That should make it work.

**Comment by gatoborrachon** [comment]
oh, i have git, i will try the first option
EDIT 1: i got this issue: https://pastebin.com/U1yVEY9X

EDIT 2: I tried the second option and worked, so i think all is fixed (or re-open the issue if you consider it correct)
