### ISSUE TITLE
Warm clothing

### ISSUE THREAD

**Issue by DcNdrew** [Enginecrafter77/SurvivalInc#4]
Here are some clothes from other mods that should have an insulation value associated with them.

* Better Animals Plus
  * Wolf Capes
  * Bear Capes
* Tinkers' Compendium
  * Wool Armor
* Construct's Armory
  * Wool Armor

**Comment by Enginecrafter77** [comment]
Not exactly as you wanted, but it is now doable. You can now specify armor material <=> conductivity bindings in the config under Heat category. This way, you can define the bindings you described yourself without adding optional dependencies for the mod. As such, I am closing this issue.
