### ISSUE TITLE
Hunger and thirst value cannot change position

### ISSUE THREAD

**Issue by ainlzj** [Enginecrafter77/SurvivalInc#40]
Hunger and thirst can't change the position. The thermometer changes the position like that

**Comment by Enginecrafter77** [comment]
Hi. I am not sure why would you like to reposition the hunger bar, but this mod doesn't interfere with the hunger bar rendering at all. So afaik there is no way you can move the hunger bar unless you use other mods.

Regarding the hydration bar, the positioning config is ignored unless you disable "Hydration bar stacking" (which when set to true integrates the bar into the vanilla HUD). So just disable that option, and you should be good to go.

Or, it's still possible that I am just missing your point. Normally, it's not very good to specify an issue with just two sentences. So if you still think I am missing your point, try to elaborate on your issue as much as possible. Provide detailed description on what you want vs what is happening, and optimally include screenshots.

**Comment by Enginecrafter77** [comment]
Okay no signs of activity on this one. Reopen if needed.

**Comment by ainlzj** [comment]
Is the location of the mod GUI modified through the drawing bar YX of the configuration file?

**Comment by ainlzj** [comment]
![image](https://user-images.githubusercontent.com/66135518/130338848-dbbc9fe7-c3ac-487d-a5c4-2c0fae4eb3ea.png)
![JA)13$M()PQ8JYM_)5E3BDR](https://user-images.githubusercontent.com/66135518/130338885-cb540fd3-eae2-4e2f-9470-cabf0f86f6ea.png)
I want to change the position of HUD. The thermometer can change the position, but the thirst value can't change the position

**Comment by ainlzj** [comment]
OK, I've solved the problem
