### ISSUE TITLE
Heat Vignette displayed in creative

### ISSUE THREAD

**Issue by Enginecrafter77** [Enginecrafter77/SurvivalInc#42]
Quote from @gatoborrachon
> EDIT: Ok it is the same thing, i'm closing it, but if i can add something, why not disabling the shader when you are in creative/spectator  mode?
![2021-08-17_19 10 14](https://user-images.githubusercontent.com/61126174/129816616-fe420ede-3aae-471d-96ab-c8a25bff9a8b.png)

_Originally posted by @gatoborrachon in https://github.com/Enginecrafter77/SurvivalInc/issues/24#issuecomment-900707902_

**Comment by gatoborrachon** [comment]
This same effect but with a gray-ish color could be added when you are near to a critical level of de-hydration? (before that effect of extreme reduced FoV)

i mean, when you are near a critical level of dehydration, you should experiment effects like blur vision, slowness, etc

**Comment by Enginecrafter77** [comment]
I mentioned it in the commit message that I also added that.

**Comment by gatoborrachon** [comment]
oh, i readed the first lines too fast that i forgot about the last one, sorry and thanks.
