### ISSUE TITLE
[Issue] Render mess in Inventory when the shaders of heating and freezing are being applied

### ISSUE THREAD

**Issue by gatoborrachon** [Enginecrafter77/SurvivalInc#44]
**Describe the bug**
When the new shaders are taking effect (when you are starting to freeze or heat) the player model in the Inventory gets a small render bug

**To Reproduce**
1. Be on a cold temperature or hot one to activate the shaders (you can remove temperature with the feather fan)
2. Check the player model in the inventory

**Expected behavior**
No render issue in the playermodel of the inventory

**Screenshots**
On a modpack:
![2021-08-20_20 51 38](https://user-images.githubusercontent.com/61126174/130307687-acc12915-7815-4bd3-8b7b-f0f77df9bf81.png)

Just Survival Inc:
![2021-08-20_21 26 20](https://user-images.githubusercontent.com/61126174/130307690-b6a32cee-6aeb-4238-ab27-3d5519a2a6e3.png)

**Game Details:**
 * Forge Version: 14.23.5.2854
 *Survival Inc: [This one](https://jitpack.io/com/github/Enginecrafter77/SurvivalInc/4c282c7e9e/SurvivalInc-4c282c7e9e.jar) from [this comment](https://github.com/Enginecrafter77/SurvivalInc/issues/41#issuecomment-902088154)

**Additional Notes**
no one

**Comment by Enginecrafter77** [comment]
Yes I have noticed this myself but It thought it was just some weird vanilla glitch. I will try to look into it as soon as possible.
