### ISSUE TITLE
The thermometer GUI disappears

### ISSUE THREAD

**Issue by ainlzj** [Enginecrafter77/SurvivalInc#49]
When I added ignitehud mod, the thermometer GUI disappeared, but the thirsty GUI was still there

![~X(`HNO6L9%W1O5ZS0L``ZU](https://user-images.githubusercontent.com/66135518/135721044-cf66ad97-f7ac-4e64-a7b8-f0eff4347933.png)
![E8TE`VVJDV}Q3R$X3U5M14N](https://user-images.githubusercontent.com/66135518/135721066-91950173-37e9-4004-8312-d172088d9020.png)

**Comment by Enginecrafter77** [comment]
Duplicate of #50 (author posted twice for some reason).
