### ISSUE TITLE
Heat sources

### ISSUE THREAD

**Issue by DcNdrew** [Enginecrafter77/SurvivalInc#5]
These blocks should be heat sources when on fire:

* Dawn of Time - Builder Edition:
  * Irori
  * Open fireplace
  * Limestone fireplace
* Pyrotech:
  * Bloomery
  * Wither Forge
  * Campfire
  * Stone and Refractory Machines
  * Pit Kiln
  * Stone/Brick Oven
  * Stone/Brick Sawmill
  * Stone/Brick Crucible
* Biomes O' Plenty
  * Hot Spring Water

**Comment by Enginecrafter77** [comment]
Done. Now, you can add radiant block to (nearly) any in-game block using the config. Head over to the "Heat" category, under "Block Heat Map". There, you can specify the block <=> radiated heat bindings as you like. Therefore, I am closing this issue as solved.
