### ISSUE TITLE
Alternatives to screen flicker on sanity.

### ISSUE THREAD

**Issue by MerrittK** [Enginecrafter77/SurvivalInc#54]
The hallucinations effect is dizzying and might cause seizures in photosensitive viewers.

An alternative to the static would be to add config options to change the hallucination system to look like vanilla Minecraft nausea and/or blindness.

**Comment by Enginecrafter77** [comment]
Yeah that might work. I will try to implement it when I get back to working on this mod (I hope it will be soon, time is really tight nowadays).

**Comment by Enginecrafter77** [comment]
Okay it should be resolved in that commit.
