### ISSUE TITLE
Server crash from flask

### ISSUE THREAD

**Issue by MineCinema** [Enginecrafter77/SurvivalInc#55]
**Short Description**
A short description of circumstances under which the crash happened.
Mod version SurvivalInc-1.3.0
For example: "I jumped into the sea and began to draw water into my flask underwater."

**To Reproduce**
Install the mod on the server
Take a flask in your hand
jump into the sea
Start collecting water

**Crash Report**
https://pastebin.com/UEm34AEt

**Additional Notes**
Add any other notes about the problem here.
[crash-2021-12-10_21.11.47-server.txt](https://github.com/Enginecrafter77/SurvivalInc/files/7695648/crash-2021-12-10_21.11.47-server.txt)

**Comment by Enginecrafter77** [comment]
Sorry for the late response. I know where the problem lies (IBlockProvider.getBiome is marked as client-only, idk why). I will fix it in the next commit.

**Comment by MineCinema** [comment]
> Извините за поздний ответ. Я знаю, в чем проблема ( `IBlockProvider.getBiome`помечено как «только для клиента», не знаю почему). Я исправлю это в следующем коммите.

There is still an important mistake
Synchronization of water on the server does not work.
If the player died of thirst, then he spawns on the spawn and again begins to die of thirst, his water is replenished only on the client's part.
And it outputs data to the server console

[20:55:27] [Netty Epoll Server IO # 1 / INFO]: Stat sync request received from CAHEK (ff08e98c-ea4c-11eb-8515-0cc47a811d3e); Dispatching reponse: StatSync {86d1b461-5396-11ec-bafa-0cc47a811d3e = {"survivalinc: heat": {value: 74.14267f}, "survivalinc: hydration": {value: 58.459312f}, "survivalinc: wetness": {value : 0.0f}, "survivalinc: sanity": {value: 100.0f, ticksAwake: 6760}}, ff08e98c-ea4c-11eb-8515-0cc47a811d3e = {"survivalinc: heat": {value: 69.97842f}, "survivalinc: hydration ": {value: 2.0043693f}," survivalinc: wetness ": {value: 0.0f}," survivalinc: sanity ": {value: 100.0f, ticksAwake: 13984}}}

**Comment by Enginecrafter77** [comment]
Now that I think about it I probably forgot to impelment resetting of the stats when player respawns. But I am not really sure whether I would forgot about such an important thing. It's just a few days until I come home so I will check it then. But thanks for reporting it. To be honest, the water quality system was really hastily implemented and there are already plans for decomissioning the current system and replacing it with a new one which would provide better interactions with tech-related mods.

**Comment by Enginecrafter77** [comment]
Fixed in 9cca86f8a52d30deb9427ed61c7c02e30bfefd80
