### ISSUE TITLE
TinyInv mod makes ghost energy invisible

### ISSUE THREAD

**Issue by YTFrost** [Enginecrafter77/SurvivalInc#58]
When having both Survival Inc. and TinyInv mod installed, ghost energy doesn't display at all.

To reproduce:
1. Install the latest versions of TinyInv and Survival Inc.
2. Become a ghost
3. Ghost energy is not visible

Expected behaviour:
Ghost energy hearts should probably be visible

Screenshot:
![Untitled](https://user-images.githubusercontent.com/55927438/211079920-798dc23c-79d3-4023-9b9b-c5268d444d40.png)

Game Details:
 Forge Version: 14.23.5.2859
 * Additional Mods:
    * Survival Inc. 1.3.0
    * TinyInv 1.3

Note:
I hope this mod isn't dead, it's great and I wish it was more popular <3

**Comment by YTFrost** [comment]
Hello! I tried the version you linked, but it's still bugged unfortunately.
![image](https://user-images.githubusercontent.com/55927438/211168440-88a770cf-83ea-4bb1-b76b-3d8bd656bc28.png)

**Comment by Enginecrafter77** [comment]
Okay, I will look into that in a few days. But given that the 1.3 version of TinyInv does not have public source code, it will be a bit more difficult.

In the meanwhile, if you're still up for it, try fiddling around with the "x Render Trigger" (Mod Config -> Survival Inc. -> Config -> HUD -> Render Trigger) settings in the config, I think it may help with the issue.

**Comment by YTFrost** [comment]
Correct me if I'm wrong, but there doesn't seem to be a config option for the ghost energy bar. It's there for every other stat, but not energy. Or did you mean I should fiddle with other stats and hope that fixes the energy?

**Comment by Enginecrafter77** [comment]
Oh, nevermind, my bad, I just realized for ghost energy it's hardcoded to render on HOTBAR events. I guess TinyInv takes over those. I will try to make that configurable too.

**Comment by YTFrost** [comment]
> it's hardcoded to render on HOTBAR events

It's interesting that you say that, because I did play around with the sanity renderTrigger, and setting it to HOTBAR or lower does make it disappear, and AIR or higher makes it visible again

**Comment by Enginecrafter77** [comment]
Okay I added a config option to change the ghost render trigger, now you can set it to AIR or higher so that it renders properly. If you have any more requests regarding this, feel free to reopen the issue.

**Comment by Enginecrafter77** [comment]
Oh sorry, misclick.
