### ISSUE TITLE
Can anyone edit the wiki?

### ISSUE THREAD

**Issue by YTFrost** [Enginecrafter77/SurvivalInc#59]
Hi. I'm not very experienced with GitHub, but I noticed I can edit the Wiki. (I added a small "test" footer)

I don't think it should be like that, but maybe I just missed something.

**Comment by Enginecrafter77** [comment]
Wait, you can? Well that's news to me. I mean, unless someone decides to nuke it, it should be fine. All I know is that it's basically just another git repository, so all the changes are tracked, so if anyone decides to mess it up I can just undo it.

**Comment by YTFrost** [comment]
Yeah I can lol. I can edit the pages and everything. If you don't mind that's fine, just thought I'd let you know
