### ISSUE TITLE
Allow transparency for GUI textures

### ISSUE THREAD

**Issue by YTFrost** [Enginecrafter77/SurvivalInc#60]
Hello. I often like to make custom textures for mods I use, and it seems like unfortunately Survival Inc. doesn't allow for it's textures to use transparency, unlike vanilla textures. Here is an example:
![image](https://user-images.githubusercontent.com/55927438/215352993-ed3e595b-c645-4966-be5c-73df18ff9dca.png)

**Comment by Enginecrafter77** [comment]
Hmm are you sure you got that transparency set up properly? I am pretty sure the original icons were using transparency too, so it should work. But in any case, I will check the code.

**Comment by YTFrost** [comment]
The original only uses binary transparency. Either fully transparent or empty pixel. I wanted to have a slightly transparent texture, like other parts of the screenshot

**Comment by Enginecrafter77** [comment]
Oh alright now it makes sense. I will try to fix it so it renders properly.

**Comment by Enginecrafter77** [comment]
Okay it's fixed in https://github.com/Enginecrafter77/SurvivalInc/commit/f1da36f107bf2ba86a7b4cb2d55401a6affa901a

You can download it here: https://maven.enginecrafter77.dev/general/enginecrafter77/survivalinc/survivalinc_1.12.2/1.3.0-55/survivalinc_1.12.2-1.3.0-55.jar
